### ISSUE TITLE
sintaxe arquivo .gitignore

### ISSUE THREAD

**Issue by Andrelamor** [thiagomrm/AcidenteTransito#1]
@thiagomrm boa tarde, faltou colocar a barra da pasta no arquivo `.gitignore`, onde vc menciona o `venv/` para ser omitido. pode ver exemplo em https://github.com/transparencia-mg/violencia-contra-mulher/blob/679130bccc59c5dc6544cfd7449f778e20479e2a/.gitignore#L130

**Comment by thiagomrm** [comment]
Feita alteração
